travis:
  secure:
    BINSTAR_TOKEN: curtCF1o0PB0fphhY/HF0wErsH9KMAuyK/cPmW7A1beW6a+e4tAGK76THhEsMHw1a6S9PHxDwNYz2h2X5slMcvwb29caIWOHdKyCMVM1N2BjOCfBcIH6e2Haw3EjU/X1HiCxp9BRKNLoQlYXiMkoAVT6apnpnHRRKAc9ocXTa8o1GwyaF0jysYFlb+fyXovMVig78x49UfAUcj2oMLC5H47pSPPMGjy0PJ2xXJJv+4Vn52bSCoJrTghjzvO8mbaA+Bw56wYX+eKx8lboQ65usqTbDjtTZMPZ4OwIeCHQ1gkKT9WkQc7ura0ekSvKJ29rZj3QhF/c4urU8h4RipF2aH07u1xRjtNFHGtJbZ9Bc3tPs+NE/9tHj3bXEbYGGyyHhUo2aOw15RZ8kARRW1KIAIsuTvIAmk2CHGbJ+TrWznaAQL6oKY+yYcID31xtg2OiaHvUw/IPcNnT4xKkoFCg5Lz4dx8GeL4fCktRvZXs/Jjdz/mVPdb4nedSJpBBVpcoXndEtMJAg0Xel4Wi4HQ6kn9Kj2jFWAeQJyGshdQ17lPhP9bez+e+edpKkySgm7MwSZN9Cc1vR8MGBGS6rEJwgHiKayk4HcwqCCwG/vReY2mWgCzT6Fhr7JBnxmP6V02eNHmrZYoyyV5xNHwP9yfunoNXB0WSYU+COJticPOuw5w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
