travis:
  secure:
    BINSTAR_TOKEN: VG+vBFd97geU/a0JrLTSB/TloGIY+FWmgp1kpv3wtK4wAaMk57SxarPe2iL+6a3i4GN/tkcAcfBct+uZScgjhUBXSnVr1i6DJo1nt7GWtoVyrO/X5Gnozn+1Lj2/CEUR6Ym592r3yh4GG6uu4vsMu+EA8U63OeiOzK3TeXBDBUtZu1r8/rxym5+epUt7SVrx7/LL9ZK+zD+EJRnoVcL1Qr9S1s0z9mAfdFfjRbKjnw0Pu+xKrhWcRHcVeGyaN13D5BjNuXZEmSFmVsFs1mzh4FNGb00bhv64WlxDHr2wPCUxLG9FTLqDuPsxUleKlFwABURZ7nYOb4AE2iInBOjumwd2lcM0QD2s1jwbTW7ZcHD8YYCLIWPRzcQ/HultOUPSv6RMT1hegvDAYiVRbqXkNT9yotX//edw/o1hYylqQpdOdfQcB8g2vi7Fk9SvrC5+TzNDepS8MizxcnzbkmPiLOT6edlxNUsc0vWHB64cPFVePOkjrerL5SzQ6DEuH/xDttc1rB3PSQ4FzEsaaDLEjUYz3HmfVhN3NzUC/xQxrKzp7Pg1TdqQVO7ldgAk3p5CU2h2b1ght0vje68e3f86vEgLSAfpCdUgRPxs2BRTREgfjNGECk7uYQmJMirap2MTjsnOhKdWqgPC2ZDONqmsval2VIKdobdX4VkRO4DxX0E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
